name: flutter_wallpaper_android
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.13
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.duckhoa.flutter_wallpaper_android
        pluginClass: FlutterWallpaperAndroidPlugin
